### ISSUE TITLE
UriFormatException: Invalid URI: The URI is empty.

### ISSUE THREAD

**Issue by NetlabDev** [umbraco/Umbraco.Commerce.PaymentProviders.Nets#1]
I'm currently facing an issue with Umbraco Commerce and the Nets Easy payment provider. More specifically, I'm encountering the following error: "UriFormatException: Invalid URI: The URI is empty."
I am using  version 12.0.0

**Comment by NetlabDev** [comment]
@umbracotrd  Thank you so much for your response and willingness to help! Fortunately, I've managed to resolve the issue. Nonetheless, I sincerely appreciate your assistance. Thanks again!

**Comment by umbracotrd** [comment]
I'm glad that you can solved the issue on your own. If you encounter any issue in the future, feel free to reach out to us again.
